import type { Metadata } from "next";
import { Footer } from "@/components/booking/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="h-[100dvh] bg-gray-100 flex flex-col">
      <div className="flex-1 overflow-y-auto no-scrollbar">
       {children}
      </div>
      <Footer />
    </div>
  );
}